all: clipboard.dll tmp.clipboard.h moveResult

moveResult: createDir
	move /Y clipboard.dll .\..\library\Windows\clipboard.dll && move /Y clipboard.obj .\..\library\Windows\clipboard.obj

createDir:
	if not exist .\..\library\Windows mkdir .\..\library\Windows

clipboard.dll: clipboard.obj
	cl /LD clipboard.obj

clipboard.obj: clipboard.c
	cl /c clipboard.c
	
tmp.clipboard.h: clipboard.h
	copy clipboard.h tmp.clipboard.h

.PHONY: all
